# Generated by Django 5.2.6 on 2026-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
